### ISSUE TITLE
real degrees of freedom?

### ISSUE THREAD

**Issue by Helmut01** [stla/OwenQ#1]
Hi  Stéphane,

following [your comment](https://github.com/Detlew/PowerTOST/issues/5) we considered your package for import in [PowerTOST](https://cran.r-project.org/package=PowerTOST) in the meantime. We found a 6–7times improvement of speed, which is nice though not relevant in practice.
However, we are considering it for [Power2Stage](https://cran.r-project.org/package=Power2Stage). Lots are simulations are performed there and hence, by default we use the non-central _t_ for speed reasons (up to 20times faster). One obstacle: In your package (based on Owen’s publication) only _integer_ degrees of freedom are implemented, whereas our `OwensQ()` accepts _reals_. In Power2Stage we need real dfs for parallel groups with unequal group sizes and/or unequal variances evaluated by the Welch-test (where the dfs are approximated acc. to Satterthwaite). Of course, we could use `nu <- floor(nu)` but that smells of lousy Excel.
IMHO, real dfs make sense. Try this example for a comparison:
```
library(PowerTOST)  
library(OwenQ)
nu2 <- nu1 <- seq(1, 35, 0.25)
nu2[which(nu2 != floor(nu2))] <- NA
nu2 <- as.integer(nu2)
t   <- -2.5
d   <- -5
b   <- R <- 2
res <- data.frame(nu1 = nu1, OwensQ = NA,
                  nu2 = nu2, OwenQ1 = NA)
for (i in 1:nrow(res)) {
  res$OwensQ[i] <- OwensQ(nu = res$nu1[i], t = t,
                          delta = d, b = b)   # real
  if (!is.na(res$nu2[i])) {
    res$OwenQ1[i] <- OwenQ1(nu = res$nu2[i], t = t,
                            delta = d, R = R) # integer
  }
}
res$RSE <- (res$OwenQ1 - res$OwensQ) / res$OwensQ
fivenum(res$OwensQ); fivenum(res$OwenQ1)
summary(res$RSE[!is.na(res$RSE)])
plot(res$nu1, res$OwensQ, type = "l", log = "xy", las = 1,
     xlab = "nu", ylab = "Owen\u2019s  Q")
points(res$nu2, res$OwenQ1)
legend("bottomleft", legend = c("PowerTOST \u2013 OwensQ()",
                                "OwenQ \u2013 OwenQ1()"),
       lty = c(1, 0), pch = c(NA, 1))
```
What do you think?

PS: What is the difference between `algo=1` and `algo=2`? Not explained in the man-page and inspecting the code didn’t gave us a clear answer. ;-)

**Comment by stla** [comment]
Hello @Helmut01 

I don't understand how the Owen Q-function with real df could help to calculate the power of the Welch test, because the df depends on the data, it changes for each simulation.

I don't remember the difference between the two algorithms, I have to take a look. I think `algo=2` works for large sample sizes when `algo=1` fails, but it is a bit slower.

There is an unexported function `iOwenQ1` which evaluates the Owen Q-function by numerical integration using `RcppNumerical`, it allows a non-integer df but it is slower. Take a look at [this blog post](https://laustep.github.io/stlahblog/posts/OwenQintegration.html).

**Comment by stla** [comment]
I close since you don't react. IMHO the interest of my package is not only the speed, but the accuracy for large sample sizes.
